spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: http://www.zhihu.com
          predicates:
            - Query=url,zhihu
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
##